#Do not edit this file; changes will be overwritten!
global CONTAINER_SIZE 
global K 
global M_Zero 
global SCALE 
global STAGE_L 
global UID_ORIENTATION 
K = 3 
M_Zero = 3 
SCALE = 3 
STAGE_L = 5
UID_ORIENTATION = {}

CONTAINER_SIZE = [101,51,101]