global K
global M_Zero 
global SCALE 
global STAGE_L
global Parallel
global MAX_SIZE

K = 9 #...
M_Zero = 3 #...
SCALE = 3 #...
STAGE_L = 5 #...
MAX_SIZE = 15 #...
Parallel = True #Switches parallel execution (multi-threading) on/off
